### ISSUE TITLE
A semicolon after @extend was unexpectedly removed after format

### ISSUE THREAD

**Issue by hstarorg** [ThisIsManta/vscode-stylus-supremacy#11]
In stylus code: 

```stylus
.code {
  @extend $xx;
}
```
After format: 

```
.code {
  @extend $xx
}
```
If use format, semicolon will be removed, But I want to keep the semicolon.

**Comment by ThisIsManta** [comment]
You're right. It was supposed to have a semicolon.

This has been fixed at version 0.3.5. Please update the extension.

Cheers!

**Comment by hstarorg** [comment]
Very thanks.
