### ISSUE TITLE
setting warning 'Matches multiple schemas when only one must validate.'

### ISSUE THREAD

**Issue by dobbbri** [ThisIsManta/vscode-stylus-supremacy#13]
settings.json:
"stylusSupremacy.sortProperties": "grouped",

file: 'file:///Users/sldobri/Library/Application%20Support/Code/User/settings.json'
severity: 'Warning'
message: 'Matches multiple schemas when only one must validate.'
at: '130,37'
source: ''

**Comment by ThisIsManta** [comment]
Thank you for reporting the issue.
Please spare me a few days for investigation and patching.

**Comment by ThisIsManta** [comment]
Would you mind sharing sample Stylus files? Or, this issue may happen regardless of Stylus code.

**Comment by dobbbri** [comment]
![screen shot 2017-08-17 at 15 22 12](https://user-images.githubusercontent.com/4087713/29427421-1cd031ce-8360-11e7-9ff3-88c2f893c37c.png)

**Comment by dobbbri** [comment]
the extension works fine like settings show, but the warning is in option selected.

**Comment by dobbbri** [comment]
do you see the erro show only in viscose setting when select "grouped"

**Comment by ThisIsManta** [comment]
Sorry, I was terribly busy, but I will check this out on Monday. Please bear with me.

**Comment by ThisIsManta** [comment]
It appears that JSON schema for **Stylus Supremacy** settings was written incorrectly. I will patch this tomorrow.

**Comment by ThisIsManta** [comment]
The extension [version 2.0.0](https://github.com/ThisIsManta/stylus-supremacy/releases/tag/v2.0.0) is out, which this issue has been addressed.

![image](https://user-images.githubusercontent.com/5592654/29722858-8be61762-89ec-11e7-8097-2316d14cb6a0.png)

Cheers!

**Comment by KandariAnkita** [comment]
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug Android",
            "program": "${workspaceRoot}/.vscode/App.js",
            "type": "reactnative",
            "request": "launch",
            "platform": "android",
            "sourceMaps": true
        }
       

    ]
}

why second curley bracket shown matches multiple schemas when only one must validate. how to resolve it in VS Code
