### ISSUE TITLE
Support for stylus inside Vue components

### ISSUE THREAD

**Issue by carstenhag** [ThisIsManta/vscode-stylus-supremacy#16]
Hello, seems like this Extension could be useful in mantaining my stylus files consistent (always removing semicolons, for example), but sadly as I am using Vue.js, the stylus "files" are mostly inside `.vue` files and the extension doesn't recognize these.

A Vue component file might look like this:
```vue
// App.vue
<template lang="pug">
  ...
</template>

<script>
  ...
</script>

<style lang="stylus">
  @require './stylus/main'

  .app
    margin 0 auto
</style>
```

I've got multiple components with stylus in them at [this repo](https://github.com/carstenhag/) if you want to try something out there.

**Comment by ThisIsManta** [comment]
Thanks for the info. I never use Vue, but this is interesting. I'll get back to you soon.

**Comment by ThisIsManta** [comment]
I'm opening a new [ticket in **Vetur** repo](https://github.com/vuejs/vetur/issues/456). May I know if you are using [**Vetur** extension](https://marketplace.visualstudio.com/items?itemName=octref.vetur) in VSCode?

**Comment by carstenhag** [comment]
Yep, I am using it, it's the go-to extension for Vue.

**Comment by ThisIsManta** [comment]
I'm going to close this issue as it will come true in **Vetur** extension.
