### ISSUE TITLE
del comments/default value `()` 

### ISSUE THREAD

**Issue by cddsgtc** [ThisIsManta/vscode-stylus-supremacy#18]
when format the file ,it will remove comments and also will remove some variables' value like `conditions = ()`

**Comment by ThisIsManta** [comment]
Could you share the file that got comments removed?

I don't quite understand why one wants to write `conditions = ()`. Would you enlighten me?

**Comment by cddsgtc** [comment]
@ThisIsManta 
this's part of the code.
```
$media_queries = {
  xs: 'only screen and (max-width: 374px)',
  sm: 'only screen and (min-width: 375px) and (max-width: 7678px)',
  md: 'only screen and (min-width: 769px)',
  lg: 'only screen and (min-widht: 1366px)'
};

$media($breakpoint) {
  conditions = ();//this is the line

  for $breakpoint in $media_queries {
    push(conditions, $media_queries[$breakpoint]);
  }

  conditions = join(',', conditions);

  @media conditions {
    {block};
  }
}
```

**Comment by ThisIsManta** [comment]
Could you make your sample code above work in http://stylus-lang.com/try.html, please?

Would you confirm if writing `conditions = ();` means an empty array?

**Comment by cddsgtc** [comment]
@ThisIsManta that's just some conditions string words and join the array items from $breakpoint, because there are no default empty value in the stylus,so define it as a empty mixin.
the origin code is [here](http://1pixelout.net/2015/10/02/simple-breakpoint-media-queries-with-stylus/).

**Comment by ThisIsManta** [comment]
This is fixed in [version 2.7.0](https://github.com/ThisIsManta/stylus-supremacy/releases/tag/v2.7.0).

@cddsgtc, sorry that it took so long to fix this bug. I was terribly busy.

**Comment by cddsgtc** [comment]
@ThisIsManta im waiting this for so lang and get it and update at first time, it help me a lot ,thank you so much too.
you should take a rest at the new year days.
新年快乐！happy new year!
but i still working π_π。

**Comment by daviscabral** [comment]
I am experiencing this on Atom - do I need to do anything special to have this working?

**Comment by ThisIsManta** [comment]
Bad news. Even though Atom package (extension) is mentioned in our official website, we **stopped updating** Stylus Supremacy engine many months ago.
