### ISSUE TITLE
Brace Expansion issue

### ISSUE THREAD

**Issue by SnO2WMaN** [ThisIsManta/vscode-stylus-supremacy#19]
Sorry I am terrible at English... :(

I tried to format to this stylus codes.
![code_2017-12-06_00-51-16](https://user-images.githubusercontent.com/15155608/33616423-3016a8b4-da20-11e7-9b64-490bc5fdaebd.png)

Compiled to CSS
![code_2017-12-06_01-03-18](https://user-images.githubusercontent.com/15155608/33616778-4283091a-da21-11e7-8272-9708ec7030ae.png)

but formated stylus code can't compile to CSS...
![code_2017-12-06_00-51-56](https://user-images.githubusercontent.com/15155608/33616604-b4b285ca-da20-11e7-82af-8ea1c146ed7d.png)

So please add option like "not to expand brace" or fix this issue...？

**Comment by ThisIsManta** [comment]
Hi Snowman, I believe this is a bug, which it is not supposed to chane {...} to (...). Spare me sometime to fix it.

**Comment by SnO2WMaN** [comment]
Thanks 👍  i hope it fixed.

**Comment by ThisIsManta** [comment]
This is fixed in [version 2.7.0](https://github.com/ThisIsManta/stylus-supremacy/releases/tag/v2.7.0).

@SnO2WMaN, sorry that it took so long to fix this bug. I was terribly busy.
