### ISSUE TITLE
Cursor moves to end of file when saving if "editor.formatOnSave" is true

### ISSUE THREAD

**Issue by stawberri** [ThisIsManta/vscode-stylus-supremacy#20]
Hi! I decided to try out your extension today to see if it's something I'd like to use. It seems pretty great so far, but I encountered an issue that really interferes with my workflow. I'm hoping that you could take a look at it, and that it's not just an issue on my end! That'd be a little embarrassing. 😅 

# Reproduction steps
1. Create a new Stylus file in Visual Studio Code.
2. Paste in this Stylus code.
```stylus
body{background:green;color:red}
```
3. Move your cursor between `back` and `ground`, so that it looks like `back|ground`.
4. Press `ctrl+s` to save.

For me, my cursor moved to the end of the last line.

# Expected behavior
I expected my cursor to stay in about the same position after I saved, as it does when you try doing this:

1. Create a new Stylus file in Visual Studio Code (or reuse your existing one from above).
2. Paste in my Stylus code again.
```stylus
body{background:green;color:red}
```
3. Right click between `back` and `ground`, the same spot where you moved your cursor before.
4. Select "Format Document."

For me, this kept my cursor between `back` and `ground`.

## Caveats
After further testing, I discovered that in situations where code might get shuffled around, my cursor doesn't necessarily stay exactly where it was when I select "Format Document," but it still stays in the same area. I think this is okay though, since it's not nearly as jarring as having my cursor jump to the end of the file.

## Rationale
I know that this disruption might not seem as noteworthy with such a small sample, but I can imagine that it might become a problem if I start working with larger files. I have a habit of saving a lot, and having my cursor suddenly disappear might be a little disruptive. I lose my place easily enough even with my cursor staying where I was working. 😓

# Idea for possible fix
I was worried that this might have been a problem on my end, or something silly like that, so I ended up digging through your code and searching the web. I've never tried writing a VSC extension before, so please disregard this section if it turns out I'm completely wrong and the cause is something entirely different! 😵

While I'm not confident I fully understand what it does and why it's longer than the other `provide` functions, I think that your `provideOnSaveFormattingEdits` function and this associated line might be unnecessary.

https://github.com/ThisIsManta/vscode-stylus-supremacy/blob/1abf30fec02334528a6542e06eb72ca3490454bb/edge/extension.ts#L215

If I'm reading [this page](https://code.visualstudio.com/blogs/2016/11/15/formatters-best-practices#_the-formatting-api) correctly, it seems to state at the end of the "The Formatting API" section that your `registerDocumentFormattingEditProvider` function call here should be enough to support formatting on save as well:

https://github.com/ThisIsManta/vscode-stylus-supremacy/blob/1abf30fec02334528a6542e06eb72ca3490454bb/edge/extension.ts#L206

While testing out my reproduction directions above, I did notice that it required a couple presses of undo to get my document back to the original state, and somewhere in between, it was in a state where it was formatted but my cursor was where it ended up when I selected "Format Document".

I think this might suggest that your extension is actually formatting twice on save right now, and that subscribing to the save event might not be necessary.

---

Anyways, I hope that you'll take some time to look into this issue, and that I've provided enough information for you to start fixing it if you agree that it needs to be fixed! 😄

**Comment by ThisIsManta** [comment]
Hello Pudding,

First of all, I must say it's my complete privilege to read your well written investigation essay above.

I have followed your solution, and yes, it works. Please upgrade **Stylus Supremacy** VS Code extension to [version 2.6.2](https://github.com/ThisIsManta/vscode-stylus-supremacy/releases/tag/v2.6.2).

Thank you for making Stylus Supremacy better.

Cheers!

**Comment by stawberri** [comment]
I'm happy that I was able to help. Thanks for fixing this so quickly! 😍
