### ISSUE TITLE
Single-line comments are removed when applied above hashes

### ISSUE THREAD

**Issue by tforssander** [ThisIsManta/vscode-stylus-supremacy#21]
Hi,

Thanks for an amazing plugin, been really helpful keeping my code consistent and clean.

When I apply a single-line comment above a hash, stylus-supremacy seems to remove it completely.

Tested on:

**vscode**: version 1.19.2
**Stylus Supremacy**: 2.7.0

I'm using the default stylus-supremacy configuration with `"editor.formatOnSave": true` enabled. I've tried switching some of the default configuration options to true/false without any luck.

**Before**:

```
// Grid
// ============================================================

$grid-breakpoints := {
  xs: 0
  sm: 600px
  md: 960px
  lg: 1280px
  xl: 1920px
}
```

**After**:

```
$grid-breakpoints ?= {
  xs: 0,
  sm: 600px,
  md: 960px,
  lg: 1280px,
  xl: 1920px
};

```

Same goes for this example where it should, in my opinion, keep the exclamation and the indentation:

**Before**:

```
/*!
 * Adds the given numbers together.
 */

add(a, b)
  a + b
```

**After**:

```
/*
   * Adds the given numbers together.
*/
add(a, b) {
  a + b;
}

```

Thank you!

**Comment by ThisIsManta** [comment]
Thanks for reporting the bug.

I have to admit that it is not perfect when it comes to comments because the **Stylus compiler,** which is written by someone else and being used to generate AST input to **Stylus Supremacy**, did not recognize single line comments at all.

I cannot promise you a date as I'm traveling a lot in January. But I will fix this definitely. Please bear with me.

**Comment by ThisIsManta** [comment]
@tforssander, may I know the meaning of `/*!`
**Stylus Supremacy** already supports [Javadoc](http://drjava.org/docs/user/ch10.html) comment style, for example:
```java
/**
 * document here
 */
```
Notice that there is another `*` after `/*`

**Comment by ThisIsManta** [comment]
Surprisingly, the `/*!` was converted to `/*`; see the illustration below.
![image](https://user-images.githubusercontent.com/5592654/34885154-ac0891c8-f7f1-11e7-9fae-ada93df0169c.png)

**Comment by ThisIsManta** [comment]
This is fixed at version 2.7.1.
Note that the `!` in `/*!` is still being removed after formatted. I will not fix it, unless you have a convincing reason.

**Comment by tforssander** [comment]
@ThisIsManta Thanks for the quick action on this, appreciated!

Regarding the `/*!` comment, I think the Sass documentation explains this pretty good: 

> When the first letter of a multiline comment is !, the comment will always rendered into css output even in compressed output modes. This is useful for adding Copyright notices to your generated CSS.

Thanks again!

**Comment by ThisIsManta** [comment]
Do you still want to retain `!` after formatting?

**Comment by tforssander** [comment]
@ThisIsManta I'm okay with it being omitted, just more of a notice from my point of view. I wouldn't spend too much time on it if it takes time. :)
