### ISSUE TITLE
Doesn't allow for scoped and non-scoped on same component

### ISSUE THREAD

**Issue by rossity** [ThisIsManta/vscode-stylus-supremacy#26]
It just replaces both with the first <style> tag's content

You should be able to have both on a component.

https://vue-loader.vuejs.org/guide/scoped-css.html#mixing-local-and-global-styles

**Comment by ThisIsManta** [comment]
Is this issue related to Vueter?

**Comment by rossity** [comment]
Yes it is, should have mentioned that!

**Comment by ThisIsManta** [comment]
I'm closing this as it has nothing to do with Stylus Supremacy directly, but Vueter.
Please follow up at https://github.com/vuejs/vetur/issues/736.
