### ISSUE TITLE
Update stylint to version 2.0.0

### ISSUE THREAD

**Issue by digulla** [ThisIsManta/vscode-stylus-supremacy#28]
There is a minor security issue in braces@1.8.5 which has been fixed in @2.3.2. See https://npmjs.com/advisories/786
This dependency is eventually included by stylint@1.5.9 which has had a 2.0.0 release some time ago.
Please update your dependency of stylint to 2.0.0 to get the fix.

See also: https://www.npmjs.com/package/stylint

**Comment by ThisIsManta** [comment]
Just saw this. I'll proceed shortly. Thanks!

**Comment by ThisIsManta** [comment]
Done at https://github.com/ThisIsManta/stylus-supremacy/commit/d5dc1065d673405ce05c1c193fc2329c63d7b34e
