### ISSUE TITLE
Change subtitle

### ISSUE THREAD

**Issue by mrshll** [ThisIsManta/vscode-stylus-supremacy#29]
Hey! Thanks for the great extension.

Recently, a teammate pointed out that "Supremacy" + "Make X great again" has a pretty loaded connotation in the US, and is generally associated with white supremacy.

I'd suggest removing the tagline, if you're willing.

**Comment by ThisIsManta** [comment]
Thanks for the suggestion. I'm so sorry and I'll remove the tag line accordingly.

**Comment by ThisIsManta** [comment]
Done at https://github.com/ThisIsManta/vscode-stylus-supremacy/commit/c35e72654e8eac5cb31a9fdb138b50578fac220a
