### ISSUE TITLE
formatOnSave

### ISSUE THREAD

**Issue by exdeniz** [ThisIsManta/vscode-stylus-supremacy#3]
Please add this option.

**Comment by ThisIsManta** [comment]
This is planned on the very next release, hopefully, I can do this **by this week**.
You will be informed when the time has come.

Cheers!

**Comment by ThisIsManta** [comment]
Hi @exdeniz,

This has been added at [version 0.3.0](https://github.com/ThisIsManta/vscode-stylus-supremacy/releases/tag/v0.3.0). Please update the extension.

Note that `file.autoSave` must be `"off"` while enabling `editor.formatOnSave`.

Cheers!
