### ISSUE TITLE
Subtle issue with percentage in flex

### ISSUE THREAD

**Issue by dweldon** [ThisIsManta/vscode-stylus-supremacy#33]
This:

```stylus
flex: 1 1 0
```

gets corrected to this:

```stylus
flex: 1 1 0%
```

however, the original shouldn't be altered.

Because [flex-basis](https://developer.mozilla.org/en-US/docs/Web/CSS/flex-basis) can be in absolute units, this correction actually isn't accurate. I'd imagine this is a pretty rare corner case, but I was doing some tricky flex column work and for whatever reason there's an important difference between `0` and `0%` in my particular use case.

**Comment by ThisIsManta** [comment]
Please read https://github.com/ThisIsManta/stylus-supremacy/issues/57

**Comment by dweldon** [comment]
Interesting. Sorry I didn't search the issues for `flex-basis`. I wasn't aware there was an IE issue that necessitates this change. I'll think of something to work around it.
