### ISSUE TITLE
Format document not working in versions 2.17.3 and 2.16.1

### ISSUE THREAD

**Issue by javiside** [ThisIsManta/vscode-stylus-supremacy#41]
My format document feature in VS Code no longer works.
I am getting a vs code pop up: 
"there is no formatter for 'stylus' files installed";
I am using the prettier extension.

Downgrading Manta's to version 2.16.0 fixes my issue

**Comment by ThisIsManta** [comment]
Hi,

There is a known logical error in v2.16.1, but the latest v2.17.3 should work fine. The below is the screen recording of me using v2.17.3 to format `padding` property.

https://user-images.githubusercontent.com/5592654/198502514-58d0a5e5-d22a-4bbf-85e6-5c7b1e4c6778.mp4

**Comment by semra-copper** [comment]
Had the same problem as @javiside , `VScode version 1.73`

**Comment by jerryc127** [comment]
https://github.com/ThisIsManta/stylus-supremacy/issues/105

**Comment by Creabine** [comment]
same problem as @javiside  and same solution, thank you

**Comment by ThisIsManta** [comment]
Ah, I screwed up the dependencies when I optimized it in the earlier version.

This should be fixed at **v2.17.4** 🙏
