### ISSUE TITLE
font-family and comma

### ISSUE THREAD

**Issue by exdeniz** [ThisIsManta/vscode-stylus-supremacy#6]
Font-family broken after format:
i try change setting ```"stylusSupremacy.insertSpaceAfterComma": false``` but this not effect.

```
.cardCollectionDescription
    flex 1 1 auto
    color #242424
    font-family 'graphik', Arial, Helvetica, sans-serif
    font-size 14px
    font-weight 200
    line-height 22px
    margin-bottom 20px
```
after format
```
.cardCollectionDescription
    flex 1 1 auto
    margin-bottom 20px
    color #242424
    font-family 'graphik' Arial Helvetica sans-serif
    font-size 14px
    font-weight 200
    line-height 22px
```

**Comment by ThisIsManta** [comment]
This has been fixed. Please update the extension to [version 0.3.0](https://github.com/ThisIsManta/vscode-stylus-supremacy/releases/tag/v0.3.0).

Cheers!

**Comment by ThisIsManta** [comment]
Presumably this was solved on your side, so I am closing this issue.

**Comment by exdeniz** [comment]
Yes. Work fine.
