### ISSUE TITLE
If open react file (js) plugin show error

### ISSUE THREAD

**Issue by exdeniz** [ThisIsManta/vscode-stylus-supremacy#7]
http://i.imgur.com/Hciv0uj.png

illegal unary "<", missing left-hand operand vs code

React JS for test
index.js
```
import React, { Component } from 'react'

import Button from './component/button'

class Contact extends Component {
  render() {
    return (
      <div>
        <Button />
      </div>
    )
  }
  openContact() {}
}

export default Contact

```

**Comment by exdeniz** [comment]
Ihmo, this is conflict on format js and styl onSave

**Comment by ThisIsManta** [comment]
You're right. I forgot to check file language ("stylus").

This has been fixed. Please update the extension to version 0.3.1.

Sorry for inconvenience!

**Comment by exdeniz** [comment]
Thanks. Now work is fine!
